//
//  SearchRepositoryResultResponse.swift
//  Platform
//
//  Created by Hadi Dbouk on 1/27/20.
//  Copyright © 2020 Hadi Dbouk. All rights reserved.
//

import Domain

struct SearchRepositoryResultResponse: Decodable {
  let totalCount: Int
  let items: [Repository]

  private enum CodingKeys: String, CodingKey {
    case totalCount = "total_count"
    case items
  }

  init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.totalCount = try container.decode(Int.self, forKey: .totalCount)
    self.items = try container.decode([Repository].self, forKey: .items)
  }
}

extension SearchRepositoryResultResponse {
  struct Repository: Decodable {
    public let id: SearchRepositoryResult.Repository.Identifier
    public let fullName: String
    public let stars: Int
    public let description: String?

    private enum CodingKeys: String, CodingKey {
      case id
      case fullName = "full_name"
      case stars = "watchers"
      case description
    }

    init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.id = try container.decode(SearchRepositoryResult.Repository.Identifier.self, forKey: .id)
      self.fullName = try container.decode(String.self, forKey: .fullName)
      self.stars = try container.decode(Int.self, forKey: .stars)
      self.description = try? container.decode(String.self, forKey: .description)
    }
  }
}

extension SearchRepositoryResultResponse {
  static let sample: [String: Any] = [
      "total_count": 7,
      "incomplete_results": false,
      "items": [
          [
              "id": 191370282,
              "node_id": "MDEwOlJlcG9zaXRvcnkxOTEzNzAyODI=",
              "name": "MarvelAR",
              "full_name": "hadiidbouk/MarvelAR",
              "private": false,
              "owner": [
                  "login": "hadiidbouk",
                  "id": 19314956,
                  "node_id": "MDQ6VXNlcjE5MzE0OTU2",
                  "avatar_url": "https://avatars0.githubusercontent.com/u/19314956?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/hadiidbouk",
                  "html_url": "https://github.com/hadiidbouk",
                  "followers_url": "https://api.github.com/users/hadiidbouk/followers",
                  "following_url": "https://api.github.com/users/hadiidbouk/following{/other_user}",
                  "gists_url": "https://api.github.com/users/hadiidbouk/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/hadiidbouk/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/hadiidbouk/subscriptions",
                  "organizations_url": "https://api.github.com/users/hadiidbouk/orgs",
                  "repos_url": "https://api.github.com/users/hadiidbouk/repos",
                  "events_url": "https://api.github.com/users/hadiidbouk/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/hadiidbouk/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/hadiidbouk/MarvelAR",
              "description": "MarvelAR is an iOS application that present Marvel Heroes 3D Models Using ARKit.",
              "fork": false,
              "url": "https://api.github.com/repos/hadiidbouk/MarvelAR",
              "forks_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/forks",
              "keys_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/teams",
              "hooks_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/hooks",
              "issue_events_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/issues/events{/number}",
              "events_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/events",
              "assignees_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/assignees{/user}",
              "branches_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/branches{/branch}",
              "tags_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/tags",
              "blobs_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/languages",
              "stargazers_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/stargazers",
              "contributors_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/contributors",
              "subscribers_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/subscribers",
              "subscription_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/subscription",
              "commits_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/contents/{+path}",
              "compare_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/merges",
              "archive_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/downloads",
              "issues_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/issues{/number}",
              "pulls_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/labels{/name}",
              "releases_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/releases{/id}",
              "deployments_url": "https://api.github.com/repos/hadiidbouk/MarvelAR/deployments",
              "created_at": "2019-06-11T12:47:39Z",
              "updated_at": "2019-11-20T21:56:24Z",
              "pushed_at": "2019-06-16T14:58:54Z",
              "git_url": "git://github.com/hadiidbouk/MarvelAR.git",
              "ssh_url": "git@github.com:hadiidbouk/MarvelAR.git",
              "clone_url": "https://github.com/hadiidbouk/MarvelAR.git",
              "svn_url": "https://github.com/hadiidbouk/MarvelAR",
              "homepage": nil,
              "size": 142278,
              "stargazers_count": 19,
              "watchers_count": 19,
              "language": "Swift",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 3,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 3,
              "open_issues": 0,
              "watchers": 19,
              "default_branch": "master",
              "score": 61.26017
          ],
          [
              "id": 70428277,
              "node_id": "MDEwOlJlcG9zaXRvcnk3MDQyODI3Nw==",
              "name": "marvelarte_products",
              "full_name": "vieslo82/marvelarte_products",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelarte_products",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelarte_products",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelarte_products/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelarte_products/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelarte_products/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelarte_products/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelarte_products/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelarte_products/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelarte_products/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelarte_products/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelarte_products/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelarte_products/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelarte_products/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelarte_products/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelarte_products/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelarte_products/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelarte_products/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelarte_products/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelarte_products/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelarte_products/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelarte_products/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelarte_products/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelarte_products/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelarte_products/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelarte_products/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelarte_products/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelarte_products/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelarte_products/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelarte_products/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelarte_products/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelarte_products/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelarte_products/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelarte_products/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelarte_products/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelarte_products/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelarte_products/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelarte_products/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelarte_products/deployments",
              "created_at": "2016-10-09T20:23:03Z",
              "updated_at": "2016-10-09T20:36:45Z",
              "pushed_at": "2016-10-09T20:36:43Z",
              "git_url": "git://github.com/vieslo82/marvelarte_products.git",
              "ssh_url": "git@github.com:vieslo82/marvelarte_products.git",
              "clone_url": "https://github.com/vieslo82/marvelarte_products.git",
              "svn_url": "https://github.com/vieslo82/marvelarte_products",
              "homepage": nil,
              "size": 2376,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "PHP",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 18.550426
          ],
          [
              "id": 71262246,
              "node_id": "MDEwOlJlcG9zaXRvcnk3MTI2MjI0Ng==",
              "name": "marvelArte_ORM_2",
              "full_name": "vieslo82/marvelArte_ORM_2",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelArte_ORM_2",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_2/deployments",
              "created_at": "2016-10-18T15:23:02Z",
              "updated_at": "2016-10-18T15:30:01Z",
              "pushed_at": "2016-10-25T16:40:42Z",
              "git_url": "git://github.com/vieslo82/marvelArte_ORM_2.git",
              "ssh_url": "git@github.com:vieslo82/marvelArte_ORM_2.git",
              "clone_url": "https://github.com/vieslo82/marvelArte_ORM_2.git",
              "svn_url": "https://github.com/vieslo82/marvelArte_ORM_2",
              "homepage": nil,
              "size": 2658,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "PHP",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 18.131203
          ],
          [
              "id": 70517403,
              "node_id": "MDEwOlJlcG9zaXRvcnk3MDUxNzQwMw==",
              "name": "marvelArte_ORM",
              "full_name": "vieslo82/marvelArte_ORM",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelArte_ORM",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelArte_ORM",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM/deployments",
              "created_at": "2016-10-10T18:36:47Z",
              "updated_at": "2016-10-11T15:51:26Z",
              "pushed_at": "2016-10-15T18:16:21Z",
              "git_url": "git://github.com/vieslo82/marvelArte_ORM.git",
              "ssh_url": "git@github.com:vieslo82/marvelArte_ORM.git",
              "clone_url": "https://github.com/vieslo82/marvelArte_ORM.git",
              "svn_url": "https://github.com/vieslo82/marvelArte_ORM",
              "homepage": nil,
              "size": 2392,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "PHP",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 18.12705
          ],
          [
              "id": 71918367,
              "node_id": "MDEwOlJlcG9zaXRvcnk3MTkxODM2Nw==",
              "name": "marvelArte_ORM_3",
              "full_name": "vieslo82/marvelArte_ORM_3",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelArte_ORM_3",
              "description": "Separación del módulo Products en FronTend y BackEnd.",
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_3/deployments",
              "created_at": "2016-10-25T16:46:36Z",
              "updated_at": "2016-10-25T16:51:26Z",
              "pushed_at": "2016-11-02T18:44:06Z",
              "git_url": "git://github.com/vieslo82/marvelArte_ORM_3.git",
              "ssh_url": "git@github.com:vieslo82/marvelArte_ORM_3.git",
              "clone_url": "https://github.com/vieslo82/marvelArte_ORM_3.git",
              "svn_url": "https://github.com/vieslo82/marvelArte_ORM_3",
              "homepage": nil,
              "size": 2676,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "PHP",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 17.5492
          ],
          [
              "id": 71262195,
              "node_id": "MDEwOlJlcG9zaXRvcnk3MTI2MjE5NQ==",
              "name": "marvelArte_Model",
              "full_name": "vieslo82/marvelArte_Model",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelArte_Model",
              "description": nil,
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelArte_Model",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelArte_Model/deployments",
              "created_at": "2016-10-18T15:22:40Z",
              "updated_at": "2016-10-18T15:22:40Z",
              "pushed_at": "2016-10-18T15:22:41Z",
              "git_url": "git://github.com/vieslo82/marvelArte_Model.git",
              "ssh_url": "git@github.com:vieslo82/marvelArte_Model.git",
              "clone_url": "https://github.com/vieslo82/marvelArte_Model.git",
              "svn_url": "https://github.com/vieslo82/marvelArte_Model",
              "homepage": nil,
              "size": 0,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": nil,
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 17.536098
          ],
          [
              "id": 72765062,
              "node_id": "MDEwOlJlcG9zaXRvcnk3Mjc2NTA2Mg==",
              "name": "marvelArte_ORM_4",
              "full_name": "vieslo82/marvelArte_ORM_4",
              "private": false,
              "owner": [
                  "login": "vieslo82",
                  "id": 12464537,
                  "node_id": "MDQ6VXNlcjEyNDY0NTM3",
                  "avatar_url": "https://avatars1.githubusercontent.com/u/12464537?v=4",
                  "gravatar_id": "",
                  "url": "https://api.github.com/users/vieslo82",
                  "html_url": "https://github.com/vieslo82",
                  "followers_url": "https://api.github.com/users/vieslo82/followers",
                  "following_url": "https://api.github.com/users/vieslo82/following{/other_user}",
                  "gists_url": "https://api.github.com/users/vieslo82/gists{/gist_id}",
                  "starred_url": "https://api.github.com/users/vieslo82/starred{/owner}{/repo}",
                  "subscriptions_url": "https://api.github.com/users/vieslo82/subscriptions",
                  "organizations_url": "https://api.github.com/users/vieslo82/orgs",
                  "repos_url": "https://api.github.com/users/vieslo82/repos",
                  "events_url": "https://api.github.com/users/vieslo82/events{/privacy}",
                  "received_events_url": "https://api.github.com/users/vieslo82/received_events",
                  "type": "User",
                  "site_admin": false
              ],
              "html_url": "https://github.com/vieslo82/marvelArte_ORM_4",
              "description": "Crear un Autocompletable de productos",
              "fork": false,
              "url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4",
              "forks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/forks",
              "keys_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/keys{/key_id}",
              "collaborators_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/collaborators{/collaborator}",
              "teams_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/teams",
              "hooks_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/hooks",
              "issue_events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/issues/events{/number}",
              "events_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/events",
              "assignees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/assignees{/user}",
              "branches_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/branches{/branch}",
              "tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/tags",
              "blobs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/git/blobs{/sha}",
              "git_tags_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/git/tags{/sha}",
              "git_refs_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/git/refs{/sha}",
              "trees_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/git/trees{/sha}",
              "statuses_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/statuses/{sha}",
              "languages_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/languages",
              "stargazers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/stargazers",
              "contributors_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/contributors",
              "subscribers_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/subscribers",
              "subscription_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/subscription",
              "commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/commits{/sha}",
              "git_commits_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/git/commits{/sha}",
              "comments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/comments{/number}",
              "issue_comment_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/issues/comments{/number}",
              "contents_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/contents/{+path}",
              "compare_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/compare/{base}...{head}",
              "merges_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/merges",
              "archive_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/{archive_format}{/ref}",
              "downloads_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/downloads",
              "issues_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/issues{/number}",
              "pulls_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/pulls{/number}",
              "milestones_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/milestones{/number}",
              "notifications_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/notifications{?since,all,participating}",
              "labels_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/labels{/name}",
              "releases_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/releases{/id}",
              "deployments_url": "https://api.github.com/repos/vieslo82/marvelArte_ORM_4/deployments",
              "created_at": "2016-11-03T16:31:24Z",
              "updated_at": "2016-11-03T16:44:50Z",
              "pushed_at": "2016-11-09T23:46:48Z",
              "git_url": "git://github.com/vieslo82/marvelArte_ORM_4.git",
              "ssh_url": "git@github.com:vieslo82/marvelArte_ORM_4.git",
              "clone_url": "https://github.com/vieslo82/marvelArte_ORM_4.git",
              "svn_url": "https://github.com/vieslo82/marvelArte_ORM_4",
              "homepage": nil,
              "size": 2668,
              "stargazers_count": 0,
              "watchers_count": 0,
              "language": "PHP",
              "has_issues": true,
              "has_projects": true,
              "has_downloads": true,
              "has_wiki": true,
              "has_pages": false,
              "forks_count": 0,
              "mirror_url": nil,
              "archived": false,
              "disabled": false,
              "open_issues_count": 0,
              "license": nil,
              "forks": 0,
              "open_issues": 0,
              "watchers": 0,
              "default_branch": "master",
              "score": 17.531677
          ]
      ]
  ]
}
